vim.keymap.set("n", "<leader>e", vim.cmd.Ex, { silent = true })
vim.keymap.set({ "i", "n" }, "<C-s>", "<cmd>w<CR>")
vim.keymap.set("i", "jk", "<Esc>", { silent = true })
vim.keymap.set("i", "<C-BS>", "<C-w>", { noremap = true })
vim.keymap.set("n", "<C-d>", "<C-d>zz", { noremap = true })
vim.keymap.set("n", "<C-u>", "<C-u>zz", { noremap = true })
vim.keymap.set("n", "n", "nzzzv", { noremap = true })
vim.keymap.set("n", "N", "Nzzzv", { noremap = true })
